# Generated by Django 5.2.6 on 2025-09-22 06:50

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agent",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Контактное лицо"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="agent_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Не определен"),
                    ("ward", "Я и есть подопечный"),
                    ("parent", "Мать/отец"),
                    ("guardian", "Опекун"),
                    ("relative", "Опекун"),
                ],
                null=True,
                verbose_name="Статус контактного лица",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[users.validators.birthday_validator],
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Укажите номер в формате: +7ХХХХХХХХХХ",
                        regex="^\\+7\\d{10}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="residence",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Город проживания"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Укажите корректное имя пользователя начиная с @",
                        regex="^@[a-zA-Z0-9]+(_?[a-zA-Z0-9]+)*$",
                    )
                ],
                verbose_name="Имя пользователя в Телеграм",
            ),
        ),
    ]
