volumes:
  pg_data:
  static:
  logs:

services:
  postgres:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped

  backend:
    build: ./backend/
    environment:
      DB_HOST: postgres
      ENABLE_POSTGRES_DB: true
    volumes:
      - static:/app/backend_static
      - logs:/app/logs
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres

  gateway:
    build: ./nginx/
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static:/staticfiles/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file: .env
    restart: unless-stopped
    depends_on:
      - backend