volumes:
  pg_data:
  static:
  logs:

services:
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/dist/. /frontend_static/
    volumes:
      - static/frontend_static:/frontend_static

  postgres:
    image: postgres:17
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    depends_on:
      - frontend

  backend:
    build: ./backend/
    environment:
      DB_HOST: postgres
      ENABLE_POSTGRES_DB: true
    volumes:
      - static/backend_static:/app/backend_static
      - logs:/app/logs
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres

  bot:
    build:
      context: ./backend/
      dockerfile: Dockerfile_Bot
    environment:
      DB_HOST: postgres
      ENABLE_POSTGRES_DB: true
    volumes:
      - logs:/app/logs
    env_file: .env
    restart: unless-stopped
    depends_on:
      - backend

  gateway:
    build: ./nginx/
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static:/staticfiles/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file: .env
    restart: unless-stopped
    depends_on:
      - bot