# Generated by Django 5.2.6 on 2025-09-24 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=2048, verbose_name="Изображение документа"
                    ),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "updated_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="UUID последнего изменения",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("standart", "Cтандартный"),
                            ("start", "Стартовый вопрос"),
                            ("waiting_docs", "Ожидает документов"),
                        ],
                        default="standart",
                        max_length=30,
                        verbose_name="Тип вопроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Вариант ответа(None - пользовательский)",
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="questionnaire.question",
                        verbose_name="Предыдущий вопрос",
                    ),
                ),
                (
                    "next_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_answers",
                        to="questionnaire.question",
                        verbose_name="Следующий вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID опроса",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("waiting_docs", "Ожидает документов"),
                            ("processing", "В обработке"),
                            ("completed", "Завершена"),
                        ],
                        default="new",
                        max_length=25,
                        verbose_name="Статус опроса",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON структура с ответами пользователя на вопросы опроса",
                        null=True,
                        verbose_name="Результаты опроса",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания опроса"
                    ),
                ),
                (
                    "questions_version_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="UUID версии вопросов",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего изменения ветки опросов",
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys",
                        to="questionnaire.question",
                        verbose_name="Текущий вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
                "ordering": ("-created_at",),
            },
        ),
    ]
