# Generated by Django 5.2.6 on 2025-09-19 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "updated_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="UUID последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID опроса",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("new", "Новая"),
                            ("waiting_docs", "Ожидает документов"),
                            ("processing", "В обработке"),
                            ("completed", "Завершена"),
                        ],
                        default="draft",
                        max_length=25,
                        verbose_name="Статус опроса",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON структура с ответами пользователя на вопросы опроса",
                        null=True,
                        verbose_name="Результаты опроса",
                    ),
                ),
                (
                    "questions_version_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="UUID версии вопросов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания опроса"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveys",
                        to="questionnaire.question",
                        verbose_name="Текущий вопрос",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Вариант ответа(None - пользовательский)",
                    ),
                ),
                (
                    "last_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_questions",
                        to="questionnaire.question",
                        verbose_name="Предыдущий вопрос",
                    ),
                ),
                (
                    "next_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_questions",
                        to="questionnaire.question",
                        verbose_name="Следующий вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("last_question", "next_question"),
                        name="unique_last_next_question",
                    ),
                    models.UniqueConstraint(
                        fields=("last_question", "answer"),
                        name="unique_last_question_answer",
                    ),
                ],
            },
        ),
    ]
