# Generated by Django 5.2.6 on 2025-09-21 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questionnaire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddConstraint(
            model_name="answerchoice",
            constraint=models.UniqueConstraint(
                fields=("last_question", "answer"), name="unique_last_question_answer"
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["created_at"], name="questionnai_created_8177c4_idx"
            ),
        ),
    ]
