# Generated by Django 5.2.6 on 2025-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answerchoice",
            name="unique_last_next_question",
        ),
        migrations.AddConstraint(
            model_name="answerchoice",
            constraint=models.UniqueConstraint(
                fields=("last_question", "next_question", "answer"),
                name="unique_last_next_question",
            ),
        ),
    ]
