# Generated by Django 5.2.6 on 2025-09-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0002_remove_answerchoice_unique_last_next_question_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answerchoice",
            name="unique_last_next_question",
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="last_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_answer_choice",
                to="questionnaire.question",
                verbose_name="Предыдущий вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="next_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_answer_choice",
                to="questionnaire.question",
                verbose_name="Следующий вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата последнего изменения ветки опросов",
            ),
        ),
    ]
