# Generated by Django 5.2.6 on 2025-09-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("standart", "Cтандартный"),
                    ("start_web", "Стартовый вопрос для веб"),
                    ("start_telegram", "Стартовый вопрос для телеграм"),
                    ("waiting_docs", "Ожидает документов"),
                ],
                default="standart",
                max_length=30,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="answer",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Вариант ответа(None - пользовательский)",
            ),
        ),
    ]
