# Generated by Django 5.2.6 on 2025-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answerchoice",
            name="unique_last_question_answer",
        ),
        migrations.AddConstraint(
            model_name="answerchoice",
            constraint=models.UniqueConstraint(
                fields=("current_question", "answer"),
                name="unique_last_question_answer",
            ),
        ),
    ]
