# Generated by Django 5.2.6 on 2025-09-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0003_remove_answerchoice_unique_last_question_answer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="Дата последнего изменения ветки опросов",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="servey_docs", verbose_name="Изображение документа"
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs",
                        to="questionnaire.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
