# Generated by Django 5.2.6 on 2025-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0003_remove_answerchoice_unique_last_question_answer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("standart", "Cтандартный"),
                    ("start", "Стартовый вопрос"),
                    ("waiting_docs", "Ожидает документов"),
                ],
                default="standart",
                max_length=30,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
