# Generated by Django 5.2.6 on 2025-09-20 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0003_remove_answerchoice_unique_last_next_question_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["created_at"], name="questionnai_created_8177c4_idx"
            ),
        ),
    ]
