# Generated by Django 5.2.6 on 2025-09-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0003_remove_answerchoice_unique_last_question_answer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=2048, verbose_name="Изображение документа"
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs",
                        to="questionnaire.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
