# Generated by Django 5.2.6 on 2025-09-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docs",
                to="questionnaire.survey",
                verbose_name="Опрос",
            ),
        ),
    ]
