# Generated by Django 5.2.6 on 2025-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_alter_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("waiting_docs", "Ожидает документов"),
                    ("processing", "В обработке"),
                    ("completed", "Завершена"),
                ],
                default="new",
                max_length=25,
                verbose_name="Статус опроса",
            ),
        ),
    ]
