# Generated by Django 5.2.6 on 2025-10-30 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Вариант ответа(None - пользовательский)",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Новая"),
                            ("waiting_docs", "Ожидает документов"),
                            ("processing", "В обработке"),
                            ("completed", "Завершена"),
                            (None, None),
                        ],
                        default=None,
                        max_length=25,
                        null=True,
                        verbose_name="Смена статуса опроса после ответа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания комментария"
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-created_at",),
                "default_related_name": "comments",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        max_length=2048, verbose_name="Изображение документа"
                    ),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "updated_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="UUID последнего изменения",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("standart", "Cтандартный"),
                            ("start", "Стартовый вопрос"),
                            ("waiting_docs", "Ожидает документов"),
                        ],
                        default="standart",
                        max_length=30,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "external_table_field_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("User.first_name", "Имя"),
                            ("User.last_name", "Фамилия"),
                            ("User.patronymic", "Отчество"),
                            ("User.ward_first_name", "Имя"),
                            ("User.ward_last_name", "Фамилия"),
                            ("User.ward_patronymic", "Отчество"),
                            ("User.residence", "Город проживания"),
                            ("User.phone_number", "Телефонный номер"),
                            ("User.email", "Электронная почта"),
                            ("User.telegram_username", "Имя пользователя в Телеграм"),
                            (
                                "User.birthday",
                                "Дата рождения подопечного (в формате ДД.ММ.ГГГГ)",
                            ),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Имя поля по внешней таблице",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID опроса",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("waiting_docs", "Ожидает документов"),
                            ("processing", "В обработке"),
                            ("completed", "Завершена"),
                        ],
                        default="new",
                        max_length=25,
                        verbose_name="Статус опроса",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON структура с ответами пользователя на вопросы опроса",
                        null=True,
                        verbose_name="Результаты опроса",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания опроса"
                    ),
                ),
                (
                    "questions_version_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="UUID версии вопросов",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего изменения ветки опросов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
                "ordering": ("-created_at",),
            },
        ),
    ]
