# Generated by Django 5.2.6 on 2025-11-02 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questionnaire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="current_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questionnaire.question",
                verbose_name="Текущий вопрос",
            ),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="next_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_answers",
                to="questionnaire.question",
                verbose_name="Следующий вопрос",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="surveys",
                to="questionnaire.question",
                verbose_name="Текущий вопрос",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docs",
                to="questionnaire.survey",
                verbose_name="Опрос",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="questionnaire.survey",
                verbose_name="Опрос",
            ),
        ),
        migrations.AddConstraint(
            model_name="answerchoice",
            constraint=models.UniqueConstraint(
                fields=("current_question", "answer"),
                name="unique_last_question_answer",
            ),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["created_at"], name="questionnai_created_8177c4_idx"
            ),
        ),
    ]
