# Generated by Django 5.2.6 on 2025-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="external_table_field_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("User.agent", "Контактное лицо"),
                    ("User.first_name", "Имя"),
                    ("User.last_name", "Фамилия"),
                    ("User.patronymic", "Отчество"),
                    ("User.residence", "Город проживания"),
                    ("User.phone_number", "Телефонный номер"),
                    ("User.email", "Электронная почта"),
                    ("User.telegram_username", "Имя пользователя в Телеграм"),
                    (
                        "User.birthday",
                        "Дата рождения подопечного (в формате ДД.ММ.ГГГГ)",
                    ),
                ],
                max_length=30,
                null=True,
                verbose_name="Имя поля по внешней таблице",
            ),
        ),
    ]
