# Generated by Django 5.2.6 on 2025-11-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_alter_answerchoice_current_question_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerchoice",
            options={
                "ordering": ("id",),
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("id",),
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
    ]
