# Generated by Django 5.2.6 on 2025-11-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_alter_answerchoice_options_alter_question_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerchoice",
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
    ]
