# Generated by Django 5.2.6 on 2025-09-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "default_related_name": "comments",
                "ordering": ("-created_at",),
                "verbose_name": "комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
