# Generated by Django 5.2.6 on 2025-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerchoice",
            name="change_survey_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "Новая"),
                    ("waiting_docs", "Ожидает документов"),
                    ("processing", "В обработке"),
                    ("completed", "Завершена"),
                    (None, None),
                ],
                default=None,
                max_length=25,
                null=True,
                verbose_name="Смена статуса опроса после ответа",
            ),
        ),
    ]
