# Generated by Django 5.2.6 on 2025-09-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_answerchoice_change_survey_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answerchoice",
            old_name="change_survey_type",
            new_name="new_status",
        ),
    ]
