# Generated by Django 5.2.6 on 2025-11-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0008_rename_change_survey_type_answerchoice_new_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("id",),
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="current_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questionnaire.question",
                verbose_name="Текущий вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.CharField(
                max_length=2048,
                verbose_name="Путь к изображению документа на Яндекс-диске",
            ),
        ),
    ]
