# Generated by Django 5.2.6 on 2025-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0009_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerchoice",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "Новая"),
                    ("waiting_docs", "Ожидает документов"),
                    ("processing", "В обработке"),
                    ("completed", "Завершена"),
                    ("rejected", "Отклонена"),
                    (None, None),
                ],
                default=None,
                max_length=25,
                null=True,
                verbose_name="Смена статуса опроса после ответа",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("waiting_docs", "Ожидает документов"),
                    ("processing", "В обработке"),
                    ("completed", "Завершена"),
                    ("rejected", "Отклонена"),
                ],
                default="new",
                max_length=25,
                verbose_name="Статус опроса",
            ),
        ),
    ]
