# Generated by Django 5.2.6 on 2026-01-31 11:07

from django.db import migrations, models


def migrate_status_values(apps, schema_editor):
    """Переносит старые значения статусов на новые"""

    # Обновляем статусы в Survey
    Survey = apps.get_model("questionnaire", "Survey")
    Survey.objects.filter(status="new").update(status="filling_survey")
    Survey.objects.filter(status="processing").update(
        status="survey_completed"
    )

    # Обновляем статусы в AnswerChoice
    AnswerChoice = apps.get_model("questionnaire", "AnswerChoice")
    AnswerChoice.objects.filter(new_status="new").update(
        new_status="filling_survey"
    )
    AnswerChoice.objects.filter(new_status="processing").update(
        new_status="survey_completed"
    )


def reverse_migrate_status_values(apps, schema_editor):
    """Возвращает старые значения статусов (для отката миграции)"""

    # Возвращаем статусы в Survey
    Survey = apps.get_model("questionnaire", "Survey")
    Survey.objects.filter(status="filling_survey").update(status="new")
    Survey.objects.filter(status="survey_completed").update(
        status="processing"
    )

    # Возвращаем статусы в AnswerChoice
    AnswerChoice = apps.get_model("questionnaire", "AnswerChoice")
    AnswerChoice.objects.filter(new_status="filling_survey").update(
        new_status="new"
    )
    AnswerChoice.objects.filter(new_status="survey_completed").update(
        new_status="processing"
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "questionnaire",
            "0010_alter_answerchoice_new_status_alter_survey_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerchoice",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("filling_survey", "Заполнение заявки"),
                    ("waiting_docs", "Ожидает документов"),
                    ("survey_completed", "Опрос пройден"),
                    ("in_progress", "В работе"),
                    ("completed", "Завершена"),
                    ("rejected", "Отклонена"),
                    (None, None),
                ],
                default=None,
                max_length=25,
                null=True,
                verbose_name="Смена статуса опроса после ответа",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("filling_survey", "Заполнение заявки"),
                    ("waiting_docs", "Ожидает документов"),
                    ("survey_completed", "Опрос пройден"),
                    ("in_progress", "В работе"),
                    ("completed", "Завершена"),
                    ("rejected", "Отклонена"),
                ],
                default="filling_survey",
                max_length=25,
                verbose_name="Статус опроса",
            ),
        ),
        migrations.RunPython(
            migrate_status_values, reverse_migrate_status_values
        ),
    ]
