# Generated by Django 5.2.6 on 2025-10-30 11:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="last name"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "ward_first_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Подопечный. Имя",
                    ),
                ),
                (
                    "ward_last_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Подопечный. Фамилия",
                    ),
                ),
                (
                    "ward_patronymic",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Подопечный. Отчество",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "agent_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "Не определен"),
                            ("ward", "Я и есть подопечный"),
                            ("parent", "Мать/отец"),
                            ("guardian", "Опекун"),
                            ("relative", "Опекун"),
                        ],
                        null=True,
                        verbose_name="Статус контактного лица",
                    ),
                ),
                (
                    "birthday",
                    models.CharField(
                        blank=True,
                        null=True,
                        validators=[users.validators.birthday_validator],
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "residence",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Город проживания",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Укажите номер в формате: +7ХХХХХХХХХХ",
                                regex="^\\+7\\d{10}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Укажите корректное имя пользователя начиная с @",
                                regex="^@[a-zA-Z0-9]+(_?[a-zA-Z0-9]+)*$",
                            )
                        ],
                        verbose_name="Имя пользователя в Телеграм",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователя",
                "verbose_name_plural": "Пользователи",
                "ordering": ("id",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("email__isnull", False),
                            models.Q(("email", ""), _negated=True),
                        ),
                        fields=("email",),
                        name="unique_non_empty_email",
                    )
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
