# Generated by Django 5.2.6 on 2025-09-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_birthday_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.AddField(
            model_name="user",
            name="ward_first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Контактное лицо. Имя",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ward_last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Контактное лицо. Фамилия",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ward_patronymic",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Контактное лицо. Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
    ]
