# Generated by Django 5.2.6 on 2025-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_agent_remove_user_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ward_first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Подопечный. Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ward_last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Подопечный. Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ward_patronymic",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Подопечный. Отчество",
            ),
        ),
    ]
