# Generated by Django 5.2.6 on 2025-09-27 13:34

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_ward_first_name_alter_user_ward_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[users.validators.birthday_validator],
                verbose_name="Дата рождения",
            ),
        ),
    ]
