# Generated by Django 5.2.6 on 2025-11-03 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Укажите корректное имя пользователя начиная с @",
                        regex="^(?:@[a-zA-Z0-9]+(_?[a-zA-Z0-9]+)*|нет)$",
                    )
                ],
                verbose_name="Имя пользователя в Телеграм",
            ),
        ),
    ]
